# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  workflow_dispatch:

jobs:
  publish:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Pack ProcRoll
      run: dotnet pack ./src/ProcRoll/ProcRoll.csproj -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --verbosity normal
      
    - name: Pack ProcRoll.Process
      run: dotnet pack ./src/ProcRoll.Process/ProcRoll.Process.csproj -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --no-build --verbosity normal

    - name: Save Packages
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: |
          ./src/**/*.nupkg
          ./src/**/*.snupkg
        
    - name: Push to Nuget
      run: dotnet nuget push .\src\**\*.nupkg -s https://api.nuget.org/v3/index.json -k $env:API_KEY
      env:
        API_KEY: ${{ secrets.PROCROLL_NUGET_API_KEY }}
